# Python cơ bản

## Các kiểu dữ liệu khác nhau: Float, int, str.

- Float: Số thực, 8 bytes (64 bits) 
- Int: Số nguyên, 8 bytes (64 bits)
- String: Chuỗi ký tự, không giới hạn độ dài, độ dài phụ thuộc vào số ký tự trong `char[]`, 1 `char` = 1 byte.

## Các phép tính `+,  -,  *, **,  //,  %,  /,  &, |`

- `+`: Cộng
- `-`: Trừ
- `*`: Nhân
- `**`: Bình phương
- `//`: Làm tròn xuống
- `%`: Lấy phần dư
- `/`: Chia
- `&`: phép AND
- `|`: phép OR

## Các kiểu cấu trúc CSDL cơ bản: `List`, `tuple`, `set`, `dictionary`

|              | list                                                                               | tuple                                                                                  | set                                             | dictionary                                                |
| ------------ | ---------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------- | ----------------------------------------------- | --------------------------------------------------------- |
| KN           | \- Dữ liệu không đồng nhất<br>\- Lưu các phần tử 1 hàng, hoặc nhiều hàng nhiều cột | \- Dữ liệu không đồng nhất<br>\- Cũng có thể lưu các phần tử hoặc nhiều hàng nhiều cột | \- Dữ liệu không đồng nhất<br>\- Lưu ở 1 hàng   | \- Dữ liệu không đồng nhất<br>\- Lưu dạng key-value pairs |
| Ký hiệu      | \[…\]                                                                              | (…)                                                                                    | {…}                                             | {…}                                                       |
|              | Allow duplicate                                                                    | Allow duplicate                                                                        | Not allow duplicate                             | Allow duplicate                                           |
|              | Có thể lồng nhau                                                                   | Có thể lồng nhau                                                                       | Có thể lồng nhau                                | Có thể lồng nhau                                          |
| Example      | \[1,2,3\]                                                                          | (element1, element2)                                                                   | {1,2,3,4,5}                                     | {“key1”: “value1”, “key2”:”value2”}                       |
| Access       | Via index                                                                          | Via index                                                                              | Must be converted to list and access over index | over keys                                                 |
| Create empty | l = \[\]                                                                           | t = ()                                                                                 | a = set()                                       | d = {}                                                    |

## Đọc, ghi và xử lý text file.

```python
with open(example1, 'r') as file1:
    FileContent = file1.read()
    print(FileContent)
```

 - 'r': Read
 - 'w': Write
 - 'a': Append
 - 'r+': Read and write
 - 'w+': Read and write
 - 'a+': Read and write
  
Ngoài ra có một vài phương thức cần chú ý:
- `.tell()`: Lấy vị trí hiện tại của con trỏ trong file.
- `.seek(offset, from_where)`: Đặt con trỏ trong file tại vị trí offset, từ vị trí from_where.

## Vòng lặp, câu lệnh có điều kiện, cấu trúc xử lý exception (try-except).

- Conditional Statements: `if-elif-else`

```python
def check_number(n):
    if n == 0:
        print("n is zero")
    elif n < 0:
        print("n is negative")
    else:
        print("n is positive")
```

<br>

- `for` loops
  
```python
for i in [1, 3, 5, 7, 9]:
    # print i in the same line
    print(i, end=" ")
```

<br>

- `while` loops

```python
i = 0
# while loop until i is greater than 10
while i < 10:
    print(i, end=" ")
    i += 1

```

<br>

-  Loop with `else` block: Đại khái về nó như một câu lệnh nobreak; nghĩa là, khối else chỉ được thực thi nếu vòng lặp kết thúc tự nhiên mà không gặp phải câu lệnh break.




In [5]:
L = []
nmax = 30
for n in range(2, nmax):
    for factor in L:
        if n % factor == 0:
            break
    else: # no break
        L.append(n)
print(L)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]


`try-except`

In [6]:
try:
    print("do something stupid:")
    x = 1/0
except:
    print("print exception here")

do something stupid:
print exception here


## Khai báo và sử dụng hàm: Cách thông thường và cách sử dụng `lambda`.

- **Cách thông thường:**

Khai báo: 
```python
def check_odd_even(n):
    if n % 2 == 0:
        return "even"
    else:
        return "odd"
print(" 2 is ", check_odd_even(2))
```

<br>

- Note: `*args` and `**kwargs`: Flexible Arguments

Có trường hợp mà viết hàm nhưng không biết số lượng và kiểu của các tham số của hàm. Vì vậy có thể dùng `*args` và `**kwargs`.

Note:

args and kwargs với tên thế nào thực sự là không quan trọng. điều quan trọng là dấu `*`

  - `*` là biểu thị 1 list các tham số.
  - `**` theo sau là 1 dictionary các tham số.

Example:
```python
def catch_all(*listthamso, **dictionarythamso):
    print("listthamso =", listthamso)
    print("dictionarythamso =", dictionarythamso)

catch_all(1, 2, 3, a=4, b=5)
```

output: 
```python
listthamso = (1, 2, 3)
dictionarythamso = {'a': 4, 'b': 5}
```

<br>

- **Cách sử dụng `lambda` - Hàm ẩn danh :**

Ngoài cách khai báo hàm dùng `def`, còn một cách khai báo hàm khác kiểu:

```python
lambda arguments: expression
```

Example:
```python
add = lambda x, y: x + y
add(1, 2) # return 3
```

Tại sao lại có phương pháp khai báo hàm này?

Lý do chính là trong python, mọi thứ đều là `object`, do đó hàm cũng có thể được dùng để làm đối số cho hàm khác.

# Python OOP

## Định nghĩa `class` and `object`

`Class` (Lớp) là người dùng định nghĩa thiết kế cho hướng đối tượng. 

Nó đại diện cho những tập thuộc tính và phương thức chung cho tất cả các đối tượng của lớp này. 

Các class là một cách thuận tiện để biểu diễn dữ liệu vì chúng gom dữ liệu và các function (hàm) hoặc method (phương thức) liên quan mà chúng ta quan tâm vào một `object` (đối tượng).

## Khai báo và sử dụng `attribute`, `method`, `constructor`, `destructor`.

In [9]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def get_name(self):
        return self.name
    
    def __del__(self):
        print('{} is deleted'.format(self.name))

In [11]:
thai = Person("Thai", 18)
print(thai.get_name())
del thai

Thai
Thai is deleted


## Class inheritance: Ý nghĩa, cách khai báo và ứng dụng.

Kế thừa trong lập trình hướng đối tượng cho phép chúng ta khai báo lớp mới sử dụng lại các hàm và thuộc tính của lớp cha cùng các chức năng mở rộng thêm.

```python
class BaseClass:
     Body of base class

class DerivedClass(BaseClass):
     Body of derived class
```

# Python cho Khoa học dữ liệu

## Numpy trong Python

### Khai báo thư viện numpy, sự khác biệt giữa numpy và list.

- Trong python, việc thuận tiện trong khai báo dữ liệu, không phải define rõ ràng kiểu dữ liệu như ngôn ngữ `C` cũng có giá của nó. Một đối tượng thay vì chỉ lưu phần content của dữ liệu, nó còn mất thêm 1 vùng bộ nhớ để lưu thêm thông tin về đối tượng này, như `reference count`, `type of variable`, `size` ...
- Với mảng trong python, ví dụ `[True, "2", 3.0, 4]`, mảng này chứa rất nhiều dữ liệu khác nhau, rất tiện dụng cho người sử dụng nhưng cái giá của nó là khá nhiều. Mỗi object trong list đều phải lưu thêm thông tin về object đó như `reference count`, `type`..., hơn nữa, nếu có nhiều object trùng loại thì việc này sẽ gây dư thừa. Đây là sự khác biệt của `dynamic-style` list và `fixed-type` array (Numpy-style).

In [14]:
import numpy as np
np.__version__

'1.21.2'

### Một số phép xử lý đơn giản trong numpy: Indexing, slicing, khai báo mảng nhiều chiều.

In [16]:
list = np.random.randint(0, 100, size=10)
list

array([98, 50, 73, 92, 25, 18, 88, 85, 44, 11])

In [19]:
# indexing
list[0]

98

In [20]:
# slicing
list[:5] # first 5 elements

array([98, 50, 73, 92, 25])

In [22]:
multi_dimentional_list = np.array([[1,2], [3,4]])
multi_dimentional_list

array([[1, 2],
       [3, 4]])

In [23]:
multi_dimentional_list[0,0]

1

In [24]:
multi_dimentional_list[:,0]

array([1, 3])

### Các phép tính cơ bản trong numpy: Cộng trừ nhân 2 ma trận, phép tính nhân từng vị trí giữa 2 ma trận.

In [25]:
mt1 = np.array([[1,2], [3,4]])
mt2 = np.array([[5,6], [7,8]])

In [26]:
mt1

array([[1, 2],
       [3, 4]])

In [27]:
mt2

array([[5, 6],
       [7, 8]])

In [28]:
mt1+mt2

array([[ 6,  8],
       [10, 12]])

In [31]:
mt1*mt2 # Nhân từng phần tử 2 ma trận

array([[ 5, 12],
       [21, 32]])

### Các phép tính thống kê và xử lý dữ liệu trong numpy: `Mean`, `median`, `standard deviation`, `min`, `max`, `det`.

In [32]:
data = np.random.randint(0, 100, size=20)
data

array([84, 47, 72, 60, 19, 57, 31, 30, 55, 59, 76, 81, 60, 69, 42, 73, 67,
       12, 76, 33])

In [33]:
print("mean:", np.mean(data))
print("median:", np.median(data))
print("standard deviation:", np.std(data))
print("min:", np.min(data))
print("max:", np.max(data))

mean: 55.15
median: 59.5
standard deviation: 20.596783729504953
min: 12
max: 84


In [35]:
# random matrix
matrix = np.random.randint(0, 100, size=(3,3))
matrix

array([[76, 99, 83],
       [ 8, 17, 18],
       [14, 44, 58]])

In [36]:
# caculate det of matrix
print("det:", np.linalg.det(matrix))

det: 3218.0000000000014


### Các phép xử lý cắt/ghép array trong numpy: Cắt/nối mảng, xoay mảng, xóa mảng.

In [37]:
data = np.random.randint(0, 100, size=20)
data

array([96, 47, 21, 60, 99, 74, 72, 72, 55,  8, 87,  4, 35, 15, 43, 80, 44,
       24, 46, 75])

In [39]:
np.split(data, 4)

[array([96, 47, 21, 60, 99]),
 array([74, 72, 72, 55,  8]),
 array([87,  4, 35, 15, 43]),
 array([80, 44, 24, 46, 75])]

In [40]:
ar1, ar2 = np.split(data, 2)

In [41]:
ar1

array([96, 47, 21, 60, 99, 74, 72, 72, 55,  8])

In [42]:
ar2

array([87,  4, 35, 15, 43, 80, 44, 24, 46, 75])

In [46]:
ar3 = np.concatenate((ar1, ar2))

In [47]:
ar3

array([96, 47, 21, 60, 99, 74, 72, 72, 55,  8, 87,  4, 35, 15, 43, 80, 44,
       24, 46, 75])

In [48]:
matrix

array([[76, 99, 83],
       [ 8, 17, 18],
       [14, 44, 58]])

In [49]:
np.rot90(matrix)

array([[83, 18, 58],
       [99, 17, 44],
       [76,  8, 14]])

In [50]:
ar1

array([96, 47, 21, 60, 99, 74, 72, 72, 55,  8])

In [53]:
'''Clean data in arr1'''
np.delete(ar1, [0,1,2])

array([60, 99, 74, 72, 72, 55,  8])

In [58]:
slide_arr1 = ar1[0:9:2]


In [59]:
slide_arr1

array([96, 21, 99, 72, 55])

## Pandas với Python

### Khai báo thư viện, sự khác biệt giữa pandas và numpy/list.

- Về mặt cơ bản thì Pandas được coi là phiên bản nâng cao của 1 Numpy structure, trong đó các `row` và `column` được xác định bằng nhãn thay vì các số nguyên chỉ số.
- Có 3 cấu trúc cơ bản là `Series`, `DataFrame`, and `Index`

In [60]:
import pandas as pd
pd.__version__

'1.3.4'

### Đọc, ghi và xử lý csv/txt/xlsx file với Pandas.

- Read: `pd.read_csv()`
- Write: `pd.to_csv()`

In [66]:
df = pd.read_csv('data/president_heights.csv')
df.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

### Một số phép xử lý cơ bản trên DF: 

- `head`, 
- `summary`, 
- các phép truy xuất thông tin theo hàng/cột
- truy xuất thông tin có điều kiện đi kèm, 
- thêm cột/xóa cột trong df.

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   order       42 non-null     int64 
 1   name        42 non-null     object
 2   height(cm)  42 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 1.1+ KB


In [71]:
df.describe()

order  height(cm)
count  42.000000   42.000000
mean   22.476190  179.738095
std    13.152461    7.015869
min     1.000000  163.000000
25%    11.250000  174.250000
50%    22.000000  182.000000
75%    33.750000  183.000000
max    44.000000  193.000000

In [73]:
df.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [74]:
name = df["name"]

In [76]:
type(name)

pandas.core.series.Series

In [77]:
name.head()

0    George Washington
1           John Adams
2     Thomas Jefferson
3        James Madison
4         James Monroe
Name: name, dtype: object

In [79]:
df.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [82]:
df.loc[1]

order                  2
name          John Adams
height(cm)           170
Name: 1, dtype: object

In [83]:
df.iloc[1]

order                  2
name          John Adams
height(cm)           170
Name: 1, dtype: object

In [84]:
df.iloc[0:3]

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189

In [85]:
df.iloc[0:10:2]

order                    name  height(cm)
0      1       George Washington         189
2      3        Thomas Jefferson         189
4      5            James Monroe         183
6      7          Andrew Jackson         185
8      9  William Henry Harrison         173

In [90]:
df[df["height(cm)"] > 170]

order                    name  height(cm)
0       1       George Washington         189
2       3        Thomas Jefferson         189
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

In [92]:
df["height(m)"] = df["height(cm)"]/100
df.head()

order               name  height(cm)  height(m)
0      1  George Washington         189       1.89
1      2         John Adams         170       1.70
2      3   Thomas Jefferson         189       1.89
3      4      James Madison         163       1.63
4      5       James Monroe         183       1.83

In [94]:
df.drop(["height(cm)"], axis=1, inplace=True)

In [95]:
df.head()

order               name  height(m)
0      1  George Washington       1.89
1      2         John Adams       1.70
2      3   Thomas Jefferson       1.89
3      4      James Madison       1.63
4      5       James Monroe       1.83

### Các phép thống kê trong pd

- `Mean`, 
- `min`, 
- `median`, 
- `max`, 
- `summary`, 
- `IQR`, 
- `standard deviation`, 
- xử lý missing data và outlier.

In [105]:
# get row with mean height(m)
df[df["height(m)"] == df["height(m)"].min()]

order           name  height(m)
3      4  James Madison       1.63

In [109]:
df[df["height(m)"] == df["height(m)"].max()]

order               name  height(m)
15     16    Abraham Lincoln       1.93
33     36  Lyndon B. Johnson       1.93

In [111]:
df[df["height(m)"] == df["height(m)"].median()]

order                 name  height(m)
24     27  William Howard Taft       1.82
28     31       Herbert Hoover       1.82
34     37        Richard Nixon       1.82
40     43       George W. Bush       1.82

In [113]:
df["height(m)"].mean()

1.7973809523809516

In [115]:
df.head()

order               name  height(m)
0      1  George Washington       1.89
1      2         John Adams       1.70
2      3   Thomas Jefferson       1.89
3      4      James Madison       1.63
4      5       James Monroe       1.83

In [116]:
df.reset_index(inplace=True)
df.set_index("order", inplace=True)
df.head()

index               name  height(m)
order                                     
1          0  George Washington       1.89
2          1         John Adams       1.70
3          2   Thomas Jefferson       1.89
4          3      James Madison       1.63
5          4       James Monroe       1.83

In [117]:
df.index.name = None

In [120]:
df.drop(["index"], axis=1, inplace=True)

In [121]:
df.head()

name  height(m)
1  George Washington       1.89
2         John Adams       1.70
3   Thomas Jefferson       1.89
4      James Madison       1.63
5       James Monroe       1.83

In [122]:
df.describe()

height(m)
count  42.000000
mean    1.797381
std     0.070159
min     1.630000
25%     1.742500
50%     1.820000
75%     1.830000
max     1.930000

In [124]:
df["height(m)"].quantile(0.25)

1.7425

In [125]:
df.head()

name  height(m)
1  George Washington       1.89
2         John Adams       1.70
3   Thomas Jefferson       1.89
4      James Madison       1.63
5       James Monroe       1.83

In [126]:
popData = pd.read_csv("data/state-population.csv")
popData.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [127]:
df1 = popData.groupby("state/region").mean()
type(df1)

pandas.core.frame.DataFrame

In [128]:
df1.head()

year    population
state/region                      
AK            2001.5  4.164389e+05
AL            2001.5  2.797862e+06
AR            2001.5  1.686640e+06
AZ            2001.5  3.337577e+06
CA            2001.5  2.170908e+07

In [129]:
popData.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [132]:
popData.sort_values(by="population", ascending=False, inplace=True)

In [133]:
popData.head()

state/region   ages  year   population
2535          USA  total  2013  316128839.0
2543          USA  total  2012  313873685.0
2541          USA  total  2011  311582564.0
2539          USA  total  2010  309326295.0
2536          USA  total  2009  306771529.0

In [134]:
popData.tail()

state/region     ages  year  population
2463           PR    total  1998         NaN
2464           PR    total  1997         NaN
2465           PR  under18  1997         NaN
2466           PR    total  1999         NaN
2467           PR  under18  1999         NaN

## SKLearn với Python

## Data visualization