In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.sum(a)

21

In [4]:
np.sum(a, axis=0)

array([5, 7, 9])

In [5]:
np.sum(a, axis=1)

array([ 6, 15])

In [6]:
np.sum(a, axis=0, keepdims=True)

array([[5, 7, 9]])

In [7]:
np.sum(a, axis=1, keepdims=True)

array([[ 6],
       [15]])

![array dimention](https://i.stack.imgur.com/Z29Nn.jpg)

In [8]:
a= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a.shape

(3, 4)

In [10]:
a2 = np.sum(a, axis=0, keepdims=True)
a2

array([[15, 18, 21, 24]])

In [11]:
a2.shape

(1, 4)

In [12]:
a3 = np.sum(a, axis=1, keepdims=True)
a3

array([[10],
       [26],
       [42]])

In [13]:
a3.shape

(3, 1)

In [14]:
for num in range(6, 0, -1) :
    print(num, end = " ")

6 5 4 3 2 1 

In [15]:
x= np.array([2, 4, 6])
y= np.array([1, 2, 3])
x/y

array([2., 2., 2.])

In [16]:
x*y

array([ 2,  8, 18])

In [17]:
np.dot(x, y)

28

In [18]:
y = np.array([1,2,3])
1 - y

array([ 0, -1, -2])

In [19]:
y

array([1, 2, 3])

In [20]:
a = np.array([1,2,3])
y/a

array([1., 1., 1.])

In [21]:
range(10, 0, -1)

range(10, 0, -1)

In [28]:
for l in reversed(range(1,5)):
    print(l)

4
3
2
1
