In [21]:
import numpy as np

In [22]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.sum(a)

21

In [24]:
np.sum(a, axis=0)

array([5, 7, 9])

In [25]:
np.sum(a, axis=1)

array([ 6, 15])

In [26]:
np.sum(a, axis=0, keepdims=True)

array([[5, 7, 9]])

In [27]:
np.sum(a, axis=1, keepdims=True)

array([[ 6],
       [15]])

![array dimention](https://i.stack.imgur.com/Z29Nn.jpg)

In [28]:
a= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a.shape

(3, 4)

In [30]:
a2 = np.sum(a, axis=0, keepdims=True)
a2

array([[15, 18, 21, 24]])

In [31]:
a2.shape

(1, 4)

In [32]:
a3 = np.sum(a, axis=1, keepdims=True)
a3

array([[10],
       [26],
       [42]])

In [33]:
a3.shape

(3, 1)